# .goreleaser.yml
before:
  hooks:
  - go mod download

builds:
  -
    id: "check-restapi"
    dir: ./check-restapi
    main: ./main.go
    binary: check-restapi

  -
    id: "check-pop3"
    dir: ./check-pop3
    main: ./main.go
    binary: check-pop3

archives:
  -
    builds:
    - check-restapi
    - check-pop3
    
    replacements:
      amd64: 64-bit
      386: 32-bit
      darwin: macOS
